apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-apps
  namespace: argocd
  labels:
    app: microservices-apps
spec:
  project: default
  source:
    # URL of your Git repository
    repoURL: 'https://github.com/Varshil8227/java-microservices-DevOps.git'
    targetRevision: HEAD
    path: k8s-GitOps/microservices
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
