apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt આ ઇમેઇલ પર તને સર્ટિફિકેટ એક્સપાયરીની નોટિફિકેશન મોકલશે
    email: varshil@example.com 
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: nginx