apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: varshil1110/java-microservice-config-server:a943ad6e8a5573793addbd79392338e46a0d7cb6
          ports:
            - containerPort: 8888
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "native"
          
          # 🔥 મોટો ફિક્સ: સ્પ્રિંગ બૂટને બૂટ થવા માટે પૂરો ટાઈમ આપો
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            initialDelaySeconds: 60  # 30 થી વધારીને 60 કર્યો
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            initialDelaySeconds: 80  # 40 થી વધારીને 80 કર્યો
            periodSeconds: 20