# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: microservices-config
#   namespace: default
# data:
#   # Centralized spring cloud services URLs
#   CONFIG_SERVER_URL: "http://config-server:8888"
#   EUREKA_SERVER_URL: "http://discovery-service:8761/eureka"
#   EUREKA_HOSTNAME: "discovery-service"

#   # Database Service Host (Points to local PostgreSQL by default. In production, update this to AWS RDS endpoint)
#   DB_HOST: "database-2.cjwy64s20ypl.ap-southeast-2.rds.amazonaws.com" # e.g. database-1.c123456789.us-east-1.rds.amazonaws.com
#   DB_PORT: "5432"

#   # Kafka Message Broker Address
#   KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"

#   # Observability Address
#   ZIPKIN_URL: "http://zipkin-service:9411/api/v2/spans"

#   # Mail Server Address (Points to local MailDev by default)
#   MAIL_HOST: "maildev-service"
#   MAIL_PORT: "1025"

#   # Feign Client URLs (Routing through API Gateway)
#   CUSTOMER_SERVICE_URL: "http://gateway-service:8222/api/v1/customers"
#   PAYMENT_SERVICE_URL: "http://gateway-service:8222/api/v1/payments"
#   PRODUCT_SERVICE_URL: "http://gateway-service:8222/api/v1/products"



apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: default
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  EUREKA_SERVER_URL: "http://discovery-service:8761/eureka/"
  EUREKA_HOSTNAME: "discovery-service"
  DB_HOST: "database-2.cjwy64s20ypl.ap-southeast-2.rds.amazonaws.com"
  DB_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  ZIPKIN_URL: "http://zipkin-service:9411/api/v2/spans"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  CUSTOMER_SERVICE_URL: "http://gateway-service:8222/api/v1/customers"
  PAYMENT_SERVICE_URL: "http://gateway-service:8222/api/v1/payments"
  PRODUCT_SERVICE_URL: "http://gateway-service:8222/api/v1/products"