apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: varshil1110/java-microservice-config-server:3b3d29f42503272633048b3b0c14cbf4a6e0c9dc
          ports:
            - containerPort: 8888
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "native"
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_READINESSSTATE_ENABLED
              value: "true"
          
          # 🔥 મોટો ફિક્સ: સ્પ્રિંગ બૂટને બૂટ થવા માટે પૂરો ટાઈમ આપો
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            initialDelaySeconds: 60  # 30 થી વધારીને 60 કર્યો
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            initialDelaySeconds: 80  # 40 થી વધારીને 80 કર્યો
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: default
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: config-server
