apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: default
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  EUREKA_SERVER_URL: "http://discovery-service:8761/eureka/"
  EUREKA_HOSTNAME: "discovery-service"
  DB_HOST: "AWS_RDS_ENDPOINT"
  DB_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  ZIPKIN_URL: "http://zipkin-service:9411/api/v2/spans"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  CUSTOMER_SERVICE_URL: "http://gateway-service:8222/api/v1/customers"
  PAYMENT_SERVICE_URL: "http://gateway-service:8222/api/v1/payments"
  PRODUCT_SERVICE_URL: "http://gateway-service:8222/api/v1/products"