apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: default
  labels:
    app: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: varshil1110/java-microservice-discovery:ff77534bdf3c287047931f2b1f4c66676db5c8fa
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
              name: http
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: CONFIG_SERVER_URL
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: discovery-service
