apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: varshil1110/java-microservice-product:66c425946e001063ddee62f140bd8e238b0f2102
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8050
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: CONFIG_SERVER_URL
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_SERVER_URL
            - name: EUREKA_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_HOSTNAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: DB_PORT
            - name: DB_NAME
              value: "product"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8050
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8050
            initialDelaySeconds: 80
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
spec:
  ports:
    - port: 8050
      targetPort: 8050
  selector:
    app: product-service