apiVersion: v1
kind: Secret 
metadata:
  name: microservices-secrets
  namespace: default
type: Opaque
stringData:
  DB_USERNAME: RDS_USERNAME
  DB_PASSWORD: RDS_PASSWORDD
  MONGODB_URI_CUSTOMER: mongodb+srv://username:password@cluster0.l7sj0ph.mongodb.net/customerdb?retryWrites=true&w=majority
  MONGODB_URI_NOTIFICATION:  mongodb+srv://username:password@cluster0.l7sj0ph.mongodb.net/notificationdb?retryWrites=true&w=majority
  MAIL_USERNAME: danish@examle.com
  MAIL_PASSWORD: placeholder_smtp_password
